logstash:
  container_name: logstash
  image: logstash
  volumes:
    - /cygdrive/d/home2/project/docker-lab:/config-dir
  command: logstash -f ./config-dir/logstash.conf
redis:
  container_name: redis-pubsub
  image: redis
  ports:
    - "6379:6379"
elastic:
  container_name: read
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
